from __future__ import annotations

from fairifier.agents.knowledge_retriever import KnowledgeRetrieverAgent
from fairifier.utils.package_selection import (
    attach_package_field_catalog,
    build_document_match_text,
    complete_source_schema_coverage,
    mandatory_source_support,
    prefer_lower_burden_package_set,
    rank_packages_by_document,
    score_package_relevance,
    source_schema_matches,
    summary_to_package_record,
)


def test_field_contract_repairs_missing_legacy_package_summary_statistics():
    packages = attach_package_field_catalog(
        [
            {
                "name": "legacy assay",
                "field_count": 0,
                "mandatory_count": 0,
                "optional_count": 0,
                "sheets": [],
            }
        ],
        [
            {
                "packageName": "legacy assay",
                "label": "library strategy",
                "level": "Assay",
                "requirement": "MANDATORY",
            },
            {
                "packageName": "legacy assay",
                "label": "platform",
                "level": "Assay",
                "requirement": "OPTIONAL",
            },
        ],
    )

    assert packages[0]["sheets"] == ["Assay"]
    assert packages[0]["field_count"] == 2
    assert packages[0]["mandatory_count"] == 1
    assert packages[0]["optional_count"] == 1


def test_contract_coverage_chooses_lowest_burden_near_best_schema_match():
    source = "RNA-Seq libraries were generated by high throughput sequencing."
    packages = [
        {
            "name": "broad assay",
            "sheets": ["Assay"],
            "mandatory_count": 9,
            "mandatory_fields": [f"absent field {index}" for index in range(9)],
            "field_contract": [
                {
                    "label": "library strategy",
                    "level": "assay",
                    "definition": "Sequencing library strategy",
                    "source_matched_values": ["RNA-Seq"],
                }
            ],
        },
        {
            "name": "lean assay",
            "sheets": ["Assay"],
            "mandatory_count": 2,
            "mandatory_fields": ["platform", "instrument model"],
            "field_contract": [
                {
                    "label": "library strategy",
                    "level": "assay",
                    "definition": "Sequencing library strategy",
                    "source_matched_values": ["RNA-Seq"],
                }
            ],
        },
        {
            "name": "default",
            "sheets": ["Investigation", "Study", "Sample", "Assay"],
            "mandatory_count": 0,
            "mandatory_fields": [],
            "field_contract": [],
        },
    ]

    selected, decisions = complete_source_schema_coverage(
        ["default"], packages, source, levels=["assay"]
    )

    assert selected == ["default", "lean assay"]
    assert decisions[0]["level"] == "assay"


def test_summary_to_package_record_maps_fairds_fields():
    record = summary_to_package_record(
        {
            "name": "soil",
            "description": "MIxS soil environmental standard for terrestrial soil sampling.",
            "levels": ["Sample"],
            "fieldCount": 42,
            "requirements": {"MANDATORY": 5, "OPTIONAL": 30, "RECOMMENDED": 7},
        }
    )

    assert record["name"] == "soil"
    assert "MIxS soil" in record["description"]
    assert record["field_count"] == 42
    assert record["mandatory_count"] == 5
    assert record["optional_count"] == 30
    assert record["recommended_count"] == 7
    assert record["sheets"] == ["Sample"]
    assert record["sample_fields"] == []
    assert record["mandatory_fields"] == []


def test_attach_package_field_catalog_exposes_schema_to_selector():
    packages = [
        {
            "name": "sequencing-assay",
            "description": "Short-read sequencing assay metadata.",
            "sample_fields": [],
            "mandatory_fields": [],
        }
    ]
    fields = [
        {
            "packageName": "sequencing-assay",
            "label": "library strategy",
            "requirement": "MANDATORY",
            "level": "Assay",
            "term": {
                "definition": "Library strategy used to generate the data",
                "syntax": "(WGS|RNA-Seq|AMPLICON)",
            },
        },
        {
            "packageName": "sequencing-assay",
            "label": "library source",
            "requirement": "OPTIONAL",
        },
    ]

    enriched = attach_package_field_catalog(
        packages,
        fields,
        match_text="low-input mRNA-seq expression profiling",
    )

    assert enriched[0]["sample_fields"] == ["library strategy", "library source"]
    assert enriched[0]["mandatory_fields"] == ["library strategy"]
    assert enriched[0]["field_contract"][0]["source_matched_values"] == ["RNA-Seq"]


def test_source_schema_matches_are_derived_from_real_controlled_values():
    packages = attach_package_field_catalog(
        [
            {
                "name": "short-read-assay",
                "description": "Short-read sequencing assay metadata.",
                "sheets": ["Assay"],
            },
            {
                "name": "whole-genome-assay",
                "description": "Whole-genome sequencing assay metadata.",
                "sheets": ["Assay"],
            },
        ],
        [
            {
                "packageName": "short-read-assay",
                "label": "library strategy",
                "level": "Assay",
                "requirement": "MANDATORY",
                "term": {"syntax": "(WGS|RNA-Seq|AMPLICON)"},
            },
            {
                "packageName": "whole-genome-assay",
                "label": "assembly method",
                "level": "Assay",
                "requirement": "MANDATORY",
            },
        ],
        match_text="expression profiling with low-input mRNA-seq libraries",
    )

    matches = source_schema_matches(
        packages,
        "expression profiling with low-input mRNA-seq libraries",
    )

    assert matches[0]["package"] == "short-read-assay"
    assert matches[0]["levels"] == ["assay"]
    assert "library strategy=RNA-Seq" in matches[0]["evidence"]


def test_source_schema_matches_do_not_reward_checklist_width():
    packages = attach_package_field_catalog(
        [
            {"name": "focused-assay", "description": "Focused assay schema."},
            {"name": "wide-checklist", "description": "Broad checklist."},
        ],
        [
            {
                "packageName": "focused-assay",
                "label": "library strategy",
                "level": "Assay",
                "term": {"syntax": "(WGS|RNA-Seq|AMPLICON)"},
            },
            *[
                {
                    "packageName": "wide-checklist",
                    "label": f"library note {index}",
                    "level": "Assay",
                    "term": {"definition": "Generic library documentation"},
                }
                for index in range(20)
            ],
        ],
        match_text="low-input mRNA-seq library preparation",
    )

    matches = source_schema_matches(
        packages,
        "low-input mRNA-seq library preparation",
        min_score=1,
    )

    assert matches[0]["package"] == "focused-assay"
    assert matches[0]["score"] > matches[1]["score"]


def test_generic_controlled_values_are_not_source_schema_evidence():
    packages = attach_package_field_catalog(
        [{"name": "broad-checklist", "sheets": ["Sample"]}],
        [
            {
                "packageName": "broad-checklist",
                "label": "capture status",
                "level": "Sample",
                "requirement": "MANDATORY",
                "term": {"syntax": "(captured|other|unknown)"},
            }
        ],
        match_text="The samples were compared with other tissues.",
    )

    assert packages[0]["field_contract"][0]["source_matched_values"] == []
    assert source_schema_matches(
        packages,
        "The samples were compared with other tissues.",
    ) == []


def test_high_unsupported_mandatory_burden_prefers_lean_same_level_peer():
    broad = {
        "name": "Broad Biology Checklist",
        "description": "Broad developmental biology sample checklist.",
        "sheets": ["Sample"],
        "mandatory_count": 6,
        "mandatory_fields": [
            "geographic latitude",
            "geographic longitude",
            "environmental medium",
            "local environmental context",
            "growth medium",
            "collection date",
        ],
        "field_contract": [],
    }
    lean = {
        "name": "Lean Domain Annotation",
        "description": "Developmental biology sample annotation for embryo stages.",
        "sheets": ["Sample"],
        "mandatory_count": 0,
        "mandatory_fields": [],
        "field_contract": [
            {
                "label": "developmental stage",
                "definition": "Stage of embryo development",
            }
        ],
    }
    source = "Embryo developmental stages were profiled by RNA sequencing."

    selected, decisions = prefer_lower_burden_package_set(
        ["default", "Broad Biology Checklist"],
        [broad, lean],
        source,
    )

    assert selected == ["default", "Lean Domain Annotation"]
    assert decisions[0]["action"] == "replace"
    assert mandatory_source_support(broad, source)["unsupported_mandatory_count"] == 6


def test_comparable_method_contracts_are_not_swapped_arbitrarily():
    packages = [
        {
            "name": name,
            "description": "RNA sequencing assay contract.",
            "sheets": ["Assay"],
            "mandatory_count": 8,
            "mandatory_fields": [f"required field {index}" for index in range(8)],
            "field_contract": [],
        }
        for name in ("Method A", "Method B")
    ]

    selected, decisions = prefer_lower_burden_package_set(
        ["default", "Method A"],
        packages,
        "RNA sequencing assay",
    )

    assert selected == ["default", "Method A"]
    assert decisions == [
        {
            "package": "Method A",
            "action": "retain",
            "burden": mandatory_source_support(packages[0], "RNA sequencing assay"),
        }
    ]


def test_burden_arbitration_does_not_reward_broader_schema_wording():
    selected_package = {
        "name": "High Burden Plant Contract",
        "description": "Plant developmental biology sample metadata.",
        "sheets": ["Sample"],
        "mandatory_count": 9,
        "mandatory_fields": [f"unsupported requirement {index}" for index in range(9)],
        "field_contract": [],
    }
    broad_peer = {
        "name": "Broad Plant Contract",
        "description": (
            "Plant embryo developmental stage transcriptome RNA sequencing "
            "biological replicate sample annotation."
        ),
        "sheets": ["Sample"],
        "mandatory_count": 5,
        "mandatory_fields": [f"absent broad field {index}" for index in range(5)],
        "field_contract": [],
    }
    lean_peer = {
        "name": "Lean Development Contract",
        "description": "Embryo developmental stage annotation.",
        "sheets": ["Sample"],
        "mandatory_count": 0,
        "mandatory_fields": [],
        "field_contract": [],
    }
    source = (
        "Plant embryo developmental stages and biological replicates were "
        "profiled by RNA sequencing."
    )

    selected, decisions = prefer_lower_burden_package_set(
        ["default", "High Burden Plant Contract"],
        [selected_package, broad_peer, lean_peer],
        source,
    )

    assert selected == ["default", "Lean Development Contract"]
    assert decisions[0]["replacement"] == "Lean Development Contract"


def test_burden_arbitration_deduplicates_selected_same_level_peer():
    broad = {
        "name": "Broad Sample Contract",
        "description": "Plant embryo developmental stage metadata.",
        "sheets": ["Sample"],
        "mandatory_count": 8,
        "mandatory_fields": [f"unsupported field {index}" for index in range(8)],
        "field_contract": [],
    }
    lean = {
        "name": "Lean Sample Contract",
        "description": "Plant embryo developmental stage metadata.",
        "sheets": ["Sample"],
        "mandatory_count": 0,
        "mandatory_fields": [],
        "field_contract": [],
    }

    selected, decisions = prefer_lower_burden_package_set(
        ["default", "Broad Sample Contract", "Lean Sample Contract"],
        [broad, lean],
        "Plant embryo developmental stages were profiled.",
    )

    assert selected == ["default", "Lean Sample Contract"]
    assert decisions[0]["replacement"] == "Lean Sample Contract"


def test_attach_package_field_catalog_prioritizes_source_relevant_labels():
    packages = [{"name": "assay-schema"}]
    fields = [
        {
            "packageName": "assay-schema",
            "label": "instrument serial number",
            "requirement": "MANDATORY",
        },
        {
            "packageName": "assay-schema",
            "label": "library strategy",
            "requirement": "OPTIONAL",
        },
        {
            "packageName": "assay-schema",
            "label": "library source",
            "requirement": "OPTIONAL",
        },
    ]

    enriched = attach_package_field_catalog(
        packages,
        fields,
        match_text="RNA sequencing library strategy from a transcriptomic source",
    )

    assert set(enriched[0]["sample_fields"][:2]) == {
        "library strategy",
        "library source",
    }


def test_score_package_relevance_uses_description_not_only_name():
    package = {
        "name": "miscellaneous natural or artificial environment",
        "description": "Generic environmental metadata for mixed natural or artificial habitats.",
        "sheets": ["Sample"],
    }
    earthworm_text = build_document_match_text(
        {
            "title": "Earthworm gut microbiome in agricultural soil",
            "research_domain": "ecology",
            "keywords": ["earthworm", "soil", "microbiome"],
        }
    )
    soil_package = {
        "name": "soil",
        "description": "MIxS soil environmental standard for terrestrial soil sampling and characterisation.",
        "sheets": ["Sample"],
    }

    assert score_package_relevance(earthworm_text, soil_package) > score_package_relevance(
        earthworm_text, package
    )


def test_rank_packages_by_document_puts_relevant_packages_first():
    packages = [
        {
            "name": "human oral",
            "description": "Human oral microbiome reporting standard.",
            "sheets": ["Sample"],
        },
        {
            "name": "soil",
            "description": "MIxS soil environmental standard for terrestrial soil sampling.",
            "sheets": ["Sample"],
        },
        {
            "name": "Illumina",
            "description": "Illumina sequencing assay metadata.",
            "sheets": ["Assay"],
        },
    ]
    match_text = build_document_match_text(
        {
            "title": "RNA-seq of earthworms in contaminated soil",
            "keywords": ["rna-seq", "soil", "earthworm"],
            "methodology": "Illumina sequencing",
        }
    )

    ranked = rank_packages_by_document(packages, match_text)

    assert ranked[0]["name"] in {"soil", "Illumina"}
    assert ranked[-1]["name"] == "human oral"


def test_build_candidate_package_names_uses_description_catalog():
    kr = object.__new__(KnowledgeRetrieverAgent)
    catalog = [
        {
            "name": "soil",
            "description": "MIxS soil environmental standard for terrestrial soil sampling.",
            "sheets": ["Sample"],
        },
        {
            "name": "human oral",
            "description": "Human oral microbiome reporting standard.",
            "sheets": ["Sample"],
        },
        {
            "name": "Illumina",
            "description": "Illumina sequencing assay metadata.",
            "sheets": ["Assay"],
        },
    ]

    candidates = kr._build_candidate_package_names(
        doc_info={
            "title": "Earthworm populations in agricultural soil using Illumina",
            "keywords": ["earthworm", "soil", "illumina"],
        },
        planner_instruction=None,
        available_package_names=[pkg["name"] for pkg in catalog],
        evidence_packets=[{"value": "Lumbricus terrestris sampled from rhizosphere soil"}],
        priority_package_hints=["default"],
        excluded_package_names=set(),
        package_catalog=catalog,
    )

    assert "soil" in candidates
    assert "Illumina" in candidates
    assert "human oral" not in candidates


def test_build_candidate_package_names_caps_total_at_twelve_with_catalog():
    kr = object.__new__(KnowledgeRetrieverAgent)
    catalog = [
        {
            "name": "soil",
            "description": "MIxS soil environmental standard for terrestrial soil sampling.",
            "sheets": ["Sample"],
        },
        {
            "name": "Illumina",
            "description": "Illumina short-read sequencing assay metadata.",
            "sheets": ["Assay"],
        },
        {
            "name": "Genome",
            "description": "Whole-genome sequencing metadata.",
            "sheets": ["Assay"],
        },
        {
            "name": "sediment",
            "description": "MIxS sediment environmental standard for aquatic sediment sampling.",
            "sheets": ["Sample"],
        },
        {
            "name": "water",
            "description": "MIxS water environmental standard for aquatic sampling.",
            "sheets": ["Sample"],
        },
        {
            "name": "miscellaneous natural or artificial environment",
            "description": "Generic environmental metadata for mixed habitats.",
            "sheets": ["Sample"],
        },
    ] + [
        {
            "name": f"ranked_package_{idx}",
            "description": "Earthworm soil illumina sequencing metadata extension.",
            "sheets": ["Sample"],
        }
        for idx in range(12)
    ]
    available = [pkg["name"] for pkg in catalog]

    candidates = kr._build_candidate_package_names(
        doc_info={
            "title": "Earthworm populations in agricultural soil using Illumina",
            "keywords": ["earthworm", "soil", "illumina", "sequencing"],
            "methodology": "Illumina sequencing of soil samples",
        },
        planner_instruction=None,
        available_package_names=available,
        evidence_packets=[{"value": "Lumbricus terrestris sampled from rhizosphere soil"}],
        priority_package_hints=[],
        excluded_package_names=set(),
        package_catalog=catalog,
    )

    assert len(candidates) <= 12


def test_build_candidate_package_names_padding_includes_local_packages():
    kr = object.__new__(KnowledgeRetrieverAgent)
    catalog = [
        {
            "name": "soil",
            "description": "MIxS soil environmental standard for terrestrial soil sampling.",
            "sheets": ["Sample"],
        }
    ]

    candidates = kr._build_candidate_package_names(
        doc_info={
            "title": "Engineered PETase depolymerises polyethylene terephthalate",
            "research_domain": "biocatalysis enzyme engineering",
            "keywords": ["PETase", "PET depolymerization"],
        },
        planner_instruction="Use PETase enzyme engineering metadata fields.",
        available_package_names=["default", "soil", "petase_enzyme_engineering"],
        evidence_packets=[{"value": "LCC ICCG enzyme, Gf-PET substrate"}],
        priority_package_hints=["default"],
        excluded_package_names=set(),
        package_catalog=catalog,
        document_match_text=build_document_match_text(
            {
                "title": "Engineered PETase depolymerises polyethylene terephthalate",
                "research_domain": "biocatalysis enzyme engineering",
                "keywords": ["PETase", "PET depolymerization"],
            },
            planner_instruction="Use PETase enzyme engineering metadata fields.",
            evidence_packets=[{"value": "LCC ICCG enzyme, Gf-PET substrate"}],
        ),
    )

    assert "petase_enzyme_engineering" in candidates


def test_priority_packages_do_not_use_handwritten_domain_keyword_rules():
    kr = object.__new__(KnowledgeRetrieverAgent)
    available = [
        "default",
        "miappe",
        "plant associated",
        "Plant Sample Checklist",
        "Crop Plant sample enhanced annotation checklist",
        "Illumina",
        "Genome",
        "COMPARE-ECDC-EFSA pilot human-associated reporting standard",
    ]

    hints = kr._infer_priority_packages(
        doc_info={
            "title": "The embryonic transcriptome of Arabidopsis thaliana",
            "research_domain": "Transcriptomics",
            "keywords": ["Arabidopsis thaliana", "embryonic transcriptome", "mRNA-seq"],
        },
        planner_instruction=None,
        available_package_names=available,
        evidence_packets=[
            {
                "value": (
                    "Three biological replicates at eight developmental stages; "
                    "four RNA input amounts and three library preparation methods."
                )
            }
        ],
    )

    assert hints == ["default"]


def test_selector_result_is_not_overridden_by_planner_package_hints():
    finalized = KnowledgeRetrieverAgent._finalize_package_selection(
        ["default"],
        fallback_package_hints=["default"],
        candidate_package_names=["default", "Genome", "Plant"],
    )

    assert finalized == ["default"]


def test_selector_result_preserves_semantically_selected_packages():
    finalized = KnowledgeRetrieverAgent._finalize_package_selection(
        ["default", "short-read-assay"],
        fallback_package_hints=["default"],
        candidate_package_names=["default", "short-read-assay"],
    )

    assert finalized == ["default", "short-read-assay"]
