"""
Gradio Web UI for FAIRifier - Production Version
完整的 Gradio 界面，集成所有核心功能
"""

import gradio as gr
import asyncio
import os
import json
from pathlib import Path
from datetime import datetime
import logging
from typing import Optional, Dict, Tuple
import sys

# Add parent directories to path
sys.path.append(str(Path(__file__).parent.parent.parent.parent))

from fairifier.graph.langgraph_app import FAIRifierLangGraphApp
from fairifier.config import config, apply_env_overrides

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# Global workflow instance (cached)
_workflow_instance = None

# Global log buffer for Gradio output
_gradio_log_buffer = []
_gradio_log_lock = asyncio.Lock()


class GradioLogHandler(logging.Handler):
    """Custom logging handler that captures logs for Gradio display."""
    def __init__(self):
        super().__init__()
        self.log_buffer = []
        self.max_buffer_size = 500  # Keep last 500 lines
    
    def emit(self, record):
        """Emit a log record to buffer."""
        try:
            msg = self.format(record)
            self.log_buffer.append(msg)
            # Keep only last N lines
            if len(self.log_buffer) > self.max_buffer_size:
                self.log_buffer = self.log_buffer[-self.max_buffer_size:]
            # Also add to global buffer
            global _gradio_log_buffer
            _gradio_log_buffer.append(msg)
            if len(_gradio_log_buffer) > self.max_buffer_size:
                _gradio_log_buffer = _gradio_log_buffer[-self.max_buffer_size:]
        except Exception:
            self.handleError(record)
    
    def get_logs(self):
        """Get all logs as string."""
        return '\n'.join(self.log_buffer)
    
    def clear(self):
        """Clear log buffer."""
        self.log_buffer = []
        global _gradio_log_buffer
        _gradio_log_buffer = []


def get_workflow():
    """Get cached workflow instance."""
    global _workflow_instance
    if _workflow_instance is None:
        _workflow_instance = FAIRifierLangGraphApp()
    return _workflow_instance


def create_temp_env(
    llm_provider: str,
    llm_model: str,
    llm_temp: float,
    llm_tokens: int,
    mineru_enabled: bool,
    langsmith_key: str,
    project_id: str
) -> Path:
    """
    创建临时配置文件，覆盖默认配置
    """
    temp_env_path = config.output_path / project_id / ".env"
    temp_env_path.parent.mkdir(parents=True, exist_ok=True)

    env_content = f"""# Temporary configuration for project {project_id}
# Generated by Gradio UI

# LLM Configuration
LLM_PROVIDER={llm_provider}
LLM_MODEL={llm_model}
LLM_TEMPERATURE={llm_temp}
LLM_MAX_TOKENS={int(llm_tokens)}

# MinerU Configuration
MINERU_ENABLED={'true' if mineru_enabled else 'false'}

# LangSmith Configuration
"""
    if langsmith_key:
        env_content += f"LANGSMITH_API_KEY={langsmith_key}\n"

    temp_env_path.write_text(env_content)
    logger.info(f"📝 Created temp config: {temp_env_path}")

    return temp_env_path


def apply_user_config(
    llm_provider: str,
    llm_model: str,
    llm_temp: float,
    llm_tokens: int,
    mineru_enabled: bool,
    langsmith_key: str
):
    """
    动态应用用户配置到全局 config
    """
    # 更新全局配置
    config.llm_provider = llm_provider
    config.llm_model = llm_model
    config.llm_temperature = llm_temp
    config.llm_max_tokens = int(llm_tokens)
    config.mineru_enabled = mineru_enabled

    # 更新环境变量（用于 LangSmith 等）
    if langsmith_key:
        os.environ["LANGSMITH_API_KEY"] = langsmith_key

    logger.info(
        f"⚙️ Applied config: {llm_provider}/{llm_model}, "
        f"temp={llm_temp}, MinerU={mineru_enabled}"
    )


# ============ 核心处理函数 ============

async def process_document_stream(
    file_obj,
    project_name: str,
    llm_provider: str,
    llm_model: str,
    llm_temp: float,
    llm_tokens: int,
    mineru_enabled: bool,
    langsmith_key: str,
    progress=gr.Progress()
):
    """
    流式处理文档 - 真正的实时执行监控
    
    显示每个节点的执行情况，包括：
    - 文档转换详情（MinerU）
    - 知识检索结果
    - 元数据生成进度
    - Agent 执行状态
    - Critic 评估反馈
    - 置信度变化
    
    支持动态配置参数
    """
    if file_obj is None:
        yield "⚠️ Please upload a file first"
        return
    
    try:
        # 应用用户配置
        apply_user_config(
            llm_provider, llm_model, llm_temp,
            llm_tokens, mineru_enabled, langsmith_key
        )

        # 初始化状态
        progress(0, desc="🚀 Starting workflow...")
        output_text = "🚀 **Starting FAIRifier Workflow**\n\n"
        output_text += f"⚙️ **Configuration**:\n"
        output_text += f"- LLM: {llm_provider}/{llm_model}\n"
        output_text += f"- Temperature: {llm_temp}\n"
        output_text += f"- Max Tokens: {int(llm_tokens)}\n"
        output_text += f"- MinerU: {'Enabled' if mineru_enabled else 'Disabled'}\n\n"
        yield output_text
        await asyncio.sleep(0.3)

        # 准备文件
        file_path = file_obj.name if hasattr(file_obj, 'name') else file_obj
        project_id = f"fairifier_{datetime.now().strftime('%Y%m%d_%H%M%S')}"

        # 创建临时配置文件
        temp_env = create_temp_env(
            llm_provider, llm_model, llm_temp,
            llm_tokens, mineru_enabled, langsmith_key,
            project_id
        )

        progress(0.1, desc="📄 Initializing...")
        output_text += f"📋 **Project ID:** `{project_id}`\n"
        output_text += f"📁 **File:** {Path(file_path).name}\n"
        output_text += f"📝 **Config File:** `{temp_env}`\n\n"
        yield output_text
        await asyncio.sleep(0.3)
        
        # 确定输出目录
        output_path = config.output_path / project_id
        output_path.mkdir(parents=True, exist_ok=True)
        
        output_text += "---\n\n## 📊 Real-time Execution Monitor\n\n"
        yield output_text

        # 设置日志捕获
        log_handler = GradioLogHandler()
        log_handler.setFormatter(logging.Formatter('%(asctime)s | %(name)s | %(levelname)s | %(message)s', datefmt='%H:%M:%S'))
        
        # 添加到根日志记录器
        root_logger = logging.getLogger()
        # 移除现有的 GradioLogHandler 以避免重复
        for handler in root_logger.handlers[:]:
            if isinstance(handler, GradioLogHandler):
                root_logger.removeHandler(handler)
        root_logger.addHandler(log_handler)
        root_logger.setLevel(logging.INFO)
        
        # 清除之前的日志
        log_handler.clear()

        # 真正运行 workflow 并监控每个步骤
        try:
            workflow = get_workflow()
            start_time = datetime.now()
            step_count = 0
            last_log_count = 0

            # 使用 LangGraph 的 stream 功能获取中间状态
            # 必须提供 thread_id 以支持 checkpointer
            stream_config = {
                "configurable": {"thread_id": project_id},
                "recursion_limit": 50
            }

            async for event in workflow.workflow.astream(
                {
                    "document_path": file_path,
                    "document_content": "",
                    "document_conversion": {},
                    "output_dir": str(output_path),
                    "document_info": {},
                    "retrieved_knowledge": [],
                    "metadata_fields": [],
                    "validation_results": {},
                    "confidence_scores": {},
                    "execution_history": [],
                    "needs_human_review": False,
                    "status": "initializing"
                },
                config=stream_config
            ):
                step_count += 1
                elapsed = (datetime.now() - start_time).total_seconds()

                # 检查是否有新的日志（在解析事件之前）
                current_logs = log_handler.get_logs()
                if current_logs:
                    log_lines = current_logs.split('\n')
                    if len(log_lines) > last_log_count:
                        new_logs = '\n'.join(log_lines[last_log_count:])
                        if new_logs.strip():
                            output_text += "### 📋 Recent Logs\n"
                            output_text += "```\n" + new_logs + "\n```\n\n"
                            last_log_count = len(log_lines)
                            yield output_text  # 实时更新日志

                # 解析事件
                if isinstance(event, tuple) and len(event) >= 2:
                    node_name, node_output = event[0], event[1]

                    # 更新进度条
                    progress_val = min(step_count / 12, 0.95)
                    progress(progress_val, desc=f"{node_name}")

                    # 格式化节点信息
                    output_text += f"### 🔷 {node_name}\n"
                    output_text += f"⏱️ *Time: {elapsed:.1f}s | Step: {step_count}*\n\n"

                    if isinstance(node_output, dict):
                        # 状态信息
                        status = node_output.get("status", "")
                        if status:
                            status_icon = {
                                "initializing": "🔵",
                                "parsing": "📄",
                                "retrieving": "🔍",
                                "generating": "🧠",
                                "validating": "✅",
                                "complete": "✅",
                                "error": "❌"
                            }.get(status, "▶️")
                            output_text += f"{status_icon} **Status**: `{status}`\n\n"

                        # 文档转换信息
                        conv = node_output.get("document_conversion", {})
                        if conv.get("success"):
                            output_text += "📄 **Document Conversion**\n"
                            output_text += f"  - ✅ Success | Method: {conv.get('method', 'N/A')}\n"
                            if "total_pages" in conv:
                                output_text += f"  - Pages: {conv['total_pages']}\n"
                            if "content_length" in conv:
                                length = conv["content_length"]
                                output_text += f"  - Content: {length:,} chars\n"
                            output_text += "\n"
                        elif conv.get("error"):
                            output_text += f"❌ **Conversion Error**: {conv['error']}\n\n"

                        # 知识检索
                        knowledge = node_output.get("retrieved_knowledge", [])
                        if knowledge:
                            output_text += f"📚 **Knowledge Retrieved**: {len(knowledge)} items\n"
                            for i, item in enumerate(knowledge[:3], 1):
                                if isinstance(item, dict):
                                    output_text += f"  {i}. {item.get('title', 'N/A')}\n"
                            if len(knowledge) > 3:
                                output_text += f"  ... and {len(knowledge)-3} more\n"
                            output_text += "\n"

                        # 元数据生成
                        fields = node_output.get("metadata_fields", [])
                        if fields:
                            output_text += f"🏷️ **Metadata Generated**: {len(fields)} fields\n"
                            # 按类别统计
                            categories = {}
                            for field in fields:
                                if isinstance(field, dict):
                                    cat = field.get("isa_sheet", "unassigned")
                                    categories[cat] = categories.get(cat, 0) + 1
                            for cat, count in list(categories.items())[:5]:
                                output_text += f"  - {cat}: {count} fields\n"
                            output_text += "\n"

                        # 执行历史（最新）
                        history = node_output.get("execution_history", [])
                        if history:
                            latest = history[-1]
                            agent = latest.get("agent_name", "Unknown")
                            success = latest.get("success", False)
                            retry = latest.get("retry_count", 0)

                            icon = "✅" if success else "❌"
                            output_text += f"{icon} **Agent**: {agent}"
                            if retry > 0:
                                output_text += f" (Retry #{retry})"
                            output_text += "\n"

                            # Critic 评估
                            critic = latest.get("critic_evaluation", {})
                            if critic:
                                decision = critic.get("decision", "")
                                score = critic.get("score", 0)
                                output_text += f"  - 🤖 **Critic**: {decision} (score: {score:.2f})\n"

                                strengths = critic.get("strengths", [])
                                if strengths:
                                    output_text += f"  - ✅ Strengths: {', '.join(strengths[:2])}\n"

                                weaknesses = critic.get("weaknesses", [])
                                if weaknesses:
                                    output_text += f"  - ⚠️ Weaknesses: {', '.join(weaknesses[:2])}\n"

                                suggestions = critic.get("suggestions", [])
                                if suggestions:
                                    output_text += f"  - 💡 Suggestions: {suggestions[0]}\n"

                            output_text += "\n"

                        # 置信度
                        conf = node_output.get("confidence_scores", {})
                        if conf.get("overall"):
                            overall = conf["overall"]
                            output_text += f"🎯 **Confidence**: {overall:.1%}"
                            if "critic" in conf:
                                output_text += f" (Critic: {conf['critic']:.1%})"
                            output_text += "\n\n"

                    # 检查是否有新的日志
                    current_logs = log_handler.get_logs()
                    if current_logs and len(current_logs.split('\n')) > last_log_count:
                        new_logs = '\n'.join(current_logs.split('\n')[last_log_count:])
                        if new_logs.strip():
                            output_text += "### 📋 Recent Logs\n"
                            output_text += "```\n" + new_logs + "\n```\n\n"
                            last_log_count = len(current_logs.split('\n'))
                    
                    output_text += "---\n\n"
                    yield output_text

            # 完成 - 显示所有日志
            total_time = (datetime.now() - start_time).total_seconds()
            progress(1.0, desc="✅ Complete!")

            output_text += "## ✅ Workflow Complete!\n\n"
            output_text += f"⏱️ **Total Time**: {total_time:.1f}s\n"
            output_text += f"📊 **Total Steps**: {step_count}\n"
            output_text += f"📁 **Output**: `{output_path}`\n\n"
            
            # 显示所有日志
            all_logs = log_handler.get_logs()
            if all_logs:
                output_text += "### 📋 Complete Processing Logs\n"
                output_text += "```\n" + all_logs + "\n```\n\n"

            yield output_text
            
            # 清理日志处理器
            root_logger.removeHandler(log_handler)

        except Exception as e:
            logger.error(f"Workflow execution failed: {e}", exc_info=True)
            output_text += f"\n## ❌ Execution Error\n\n"
            output_text += f"```python\n{type(e).__name__}: {str(e)}\n```\n\n"
            
            # 显示错误日志
            all_logs = log_handler.get_logs()
            if all_logs:
                output_text += "### 📋 Error Logs\n"
                output_text += "```\n" + all_logs + "\n```\n\n"
            
            yield output_text
            
            # 清理日志处理器
            root_logger.removeHandler(log_handler)
            
    except Exception as e:
        logger.error(f"Processing failed: {e}")
        error_msg = f"❌ **Error:** {str(e)}\n\n"
        
        # 尝试获取日志
        try:
            root_logger = logging.getLogger()
            for handler in root_logger.handlers:
                if isinstance(handler, GradioLogHandler):
                    logs = handler.get_logs()
                    if logs:
                        error_msg += "### 📋 Error Logs\n```\n" + logs + "\n```\n"
                    root_logger.removeHandler(handler)
                    break
        except:
            pass
        
        yield error_msg


async def process_document_full(
    file_obj,
    project_name: str,
    llm_provider: str,
    llm_model: str,
    llm_temp: float,
    llm_tokens: int,
    mineru_enabled: bool,
    langsmith_key: str
) -> Tuple[Optional[Dict], str, str]:
    """
    完整处理（返回结构化结果用于其他标签页）
    支持动态配置参数
    """
    if file_obj is None:
        return None, "⚠️ Please upload a file first", ""
    
    try:
        # 应用用户配置
        apply_user_config(
            llm_provider, llm_model, llm_temp,
            llm_tokens, mineru_enabled, langsmith_key
        )

        file_path = file_obj.name if hasattr(file_obj, 'name') else file_obj
        project_id = f"fairifier_{datetime.now().strftime('%Y%m%d_%H%M%S')}"

        # 创建临时配置文件
        temp_env = create_temp_env(
            llm_provider, llm_model, llm_temp,
            llm_tokens, mineru_enabled, langsmith_key,
            project_id
        )

        # 输出目录
        output_path = config.output_path / project_id
        output_path.mkdir(parents=True, exist_ok=True)

        # 运行 workflow（使用更新后的 config）
        workflow = get_workflow()
        result = await workflow.run(file_path, project_id, output_dir=str(output_path))
        
        status = result.get("status", "unknown")
        
        status_msg = f"✅ Processing completed! Status: {status.upper()}"
        if result.get("needs_human_review"):
            status_msg += " (⚠️ Needs review)"
        
        # 返回: (完整结果JSON, 状态消息, 输出目录)
        return result, status_msg, str(output_path)
        
    except Exception as e:
        logger.error(f"Processing failed: {e}")
        return None, f"❌ Error: {str(e)}", ""


# ============ 结果展示函数 ============

def format_execution_history(result: Dict) -> str:
    """格式化执行历史为 Markdown 表格"""
    if not result or "execution_history" not in result:
        return "No execution history available"
    
    history = result["execution_history"]
    
    # 创建 Markdown 表格
    table = "| Step | Agent | Success | Critic Decision | Score |\n"
    table += "|------|-------|---------|-----------------|-------|\n"
    
    for i, exec_record in enumerate(history, 1):
        agent_name = exec_record.get("agent_name", "Unknown")
        success = "✅" if exec_record.get("success", False) else "❌"
        
        critic_eval = exec_record.get("critic_evaluation", {})
        decision = critic_eval.get("decision", "N/A")
        score = critic_eval.get("score", 0.0)
        score_str = f"{score:.2f}" if score else "N/A"
        
        table += f"| {i} | {agent_name} | {success} | {decision} | {score_str} |\n"
    
    return table


def format_confidence_details(result: Dict) -> str:
    """格式化置信度详情"""
    if not result or "confidence_scores" not in result:
        return "No confidence scores available"
    
    conf_scores = result["confidence_scores"]
    
    md = "## 🎯 Confidence Breakdown\n\n"
    
    # 总体置信度
    overall = conf_scores.get("overall", 0.0)
    md += f"### Overall Confidence: **{overall:.2%}**\n\n"
    
    # 各维度
    md += "### Dimensions\n\n"
    md += f"- **Critic Confidence:** {conf_scores.get('critic', 0.0):.2%}\n"
    md += f"- **Structural Confidence:** {conf_scores.get('structural', 0.0):.2%}\n"
    md += f"- **Validation Confidence:** {conf_scores.get('validation', 0.0):.2%}\n\n"
    
    # 质量指标
    if "quality_metrics" in result:
        md += "### Quality Metrics\n\n"
        md += "```json\n"
        md += json.dumps(result["quality_metrics"], indent=2)
        md += "\n```\n"
    
    return md


def format_metadata_fields(result: Dict) -> Tuple[str, str]:
    """
    格式化元数据字段
    返回: (Markdown展示, JSON字符串)
    """
    if not result or "metadata_fields" not in result:
        return "No metadata fields available", "{}"
    
    fields = result["metadata_fields"]
    if isinstance(fields, dict):
        fields = list(fields.values())
    
    # 统计
    total = len(fields)
    required = sum(1 for f in fields if isinstance(f, dict) and f.get("required", False))
    
    # 按 ISA sheet 分组
    from collections import defaultdict
    by_sheet = defaultdict(list)
    
    for field in fields:
        if isinstance(field, dict):
            sheet = field.get("isa_sheet", "unassigned")
            by_sheet[sheet].append(field)
    
    # Markdown
    md = f"## 🏷️ Metadata Fields ({total} total, {required} required)\n\n"
    
    for sheet_name in ["investigation", "study", "assay", "sample", "observationunit", "unassigned"]:
        if sheet_name not in by_sheet:
            continue
        
        sheet_fields = by_sheet[sheet_name]
        md += f"### {sheet_name.upper()} ({len(sheet_fields)} fields)\n\n"
        
        for field in sheet_fields[:10]:  # 只显示前10个
            name = field.get("field_name", "Unknown")
            required_badge = "🔴" if field.get("required") else "⚪"
            conf = field.get("confidence", 0.0)
            
            md += f"- {required_badge} **{name}** (confidence: {conf:.2%})\n"
        
        if len(sheet_fields) > 10:
            md += f"\n_... and {len(sheet_fields) - 10} more fields_\n"
        
        md += "\n"
    
    # JSON
    json_str = json.dumps({"metadata_fields": fields}, indent=2)
    
    return md, json_str


# ============ Gradio 界面 ============

def create_gradio_interface():
    """创建 Gradio 界面"""
    
    with gr.Blocks() as demo:
        
        # 标题
        gr.Markdown("""
        # 🧬 FAIRifier - FAIR Metadata Generator
        
        Automated generation of FAIR metadata from research documents using LangGraph + LLM
        
        ---
        """)
        
        # 全局状态（存储处理结果）
        result_state = gr.State(None)
        output_dir_state = gr.State("")
        
        # 主标签页
        with gr.Tabs():
            
            # ========== Tab 1: Upload & Process ==========
            with gr.Tab("📄 Upload & Process", id="upload"):
                gr.Markdown("### Upload your research document and start processing")
                
                with gr.Row():
                    with gr.Column(scale=1):
                        file_input = gr.File(
                            label="📁 Upload Document",
                            file_types=[".pdf", ".txt", ".md"],
                            type="filepath"
                        )
                        
                        project_name = gr.Textbox(
                            label="🏷️ Project Name (optional)",
                            placeholder="e.g., Earthworm Genome Study",
                            value=""
                        )
                        
                        with gr.Row():
                            process_btn = gr.Button(
                                "🚀 Process Document",
                                variant="primary",
                                size="lg"
                            )
                            gr.ClearButton(
                                components=[file_input, project_name]
                            )
                        
                        gr.Markdown("""
                        **Supported formats:**
                        - PDF (with MinerU high-fidelity parsing)
                        - Text files (.txt)
                        - Markdown (.md)
                        """)
                    
                    with gr.Column(scale=2):
                        # 流式输出显示
                        stream_output = gr.Markdown(
                            value="**Ready to process.** Upload a file and click the button above.",
                            label="Processing Progress",
                            elem_classes=["output-markdown"]
                        )
                
                # 示例文件
                example_base = Path(__file__).parent.parent.parent.parent / "examples" / "inputs"
                example_files = []
                
                # 定义示例文件及其可能的路径
                example_configs = [
                    {
                        "name": "earthworm_4n_paper_bioRxiv.pdf",
                        "display": "Earthworm 4n Paper",
                        "paths": [
                            example_base / "earthworm_4n_paper_bioRxiv.pdf",
                            example_base.parent.parent / "evaluation" / "datasets" / "raw" / "earthworm" / "earthworm_4n_paper_bioRxiv.pdf"
                        ]
                    },
                    {
                        "name": "aec8570_CombinedPDF_v1.pdf",
                        "display": "Biosensor Paper",
                        "paths": [
                            example_base / "aec8570_CombinedPDF_v1.pdf",
                            example_base.parent.parent / "evaluation" / "datasets" / "raw" / "biosensor" / "aec8570_CombinedPDF_v1.pdf"
                        ]
                    }
                ]
                
                for example_config in example_configs:
                    for path in example_config["paths"]:
                        if path.exists():
                            example_files.append([str(path), example_config["display"]])
                            break
                
                if example_files:
                    gr.Examples(
                        examples=example_files,
                        inputs=[file_input, project_name],
                        label="📚 Example Documents"
                    )
            
            # ========== Tab 2: Results Summary ==========
            with gr.Tab("📊 Results Summary", id="results"):
                gr.Markdown("### Processing Results Overview")
                
                status_display = gr.Textbox(
                    label="Status",
                    value="No results yet",
                    interactive=False
                )
                
                with gr.Row():
                    conf_critic = gr.Number(
                        label="🤖 Critic Confidence",
                        value=0,
                        interactive=False
                    )
                    conf_structural = gr.Number(
                        label="🏗️ Structural Confidence",
                        value=0,
                        interactive=False
                    )
                    conf_validation = gr.Number(
                        label="✅ Validation Confidence",
                        value=0,
                        interactive=False
                    )
                    conf_overall = gr.Number(
                        label="🎯 Overall Confidence",
                        value=0,
                        interactive=False
                    )
                
                # 执行摘要
                with gr.Row():
                    exec_total = gr.Number(
                        label="Total Steps",
                        value=0,
                        interactive=False
                    )
                    exec_success = gr.Number(
                        label="Successful Steps",
                        value=0,
                        interactive=False
                    )
                    exec_failed = gr.Number(
                        label="Failed Steps",
                        value=0,
                        interactive=False
                    )
                    exec_retry = gr.Number(
                        label="Steps with Retry",
                        value=0,
                        interactive=False
                    )
                
                # 完整结果（JSON）
                result_json = gr.JSON(
                    label="Full Results (JSON)",
                    visible=False
                )
                
                show_json_btn = gr.Button("📋 Show Full JSON")
                
                def toggle_json(visible):
                    return gr.update(visible=not visible)
                
                show_json_btn.click(
                    fn=lambda: gr.update(visible=True),
                    outputs=result_json,
                    queue=False  # 快速 UI 更新不需要队列
                )
            
            # ========== Tab 3: Execution History ==========
            with gr.Tab("🔍 Execution History", id="history"):
                gr.Markdown("### Step-by-Step Execution Timeline with Critic Evaluations")
                
                history_output = gr.Markdown(
                    value="No execution history yet. Process a document first.",
                    label="Execution Timeline"
                )
            
            # ========== Tab 4: Confidence Details ==========
            with gr.Tab("🎯 Confidence Details", id="confidence"):
                gr.Markdown("### Multi-Dimensional Confidence Analysis")
                
                confidence_output = gr.Markdown(
                    value="No confidence data yet. Process a document first.",
                    label="Confidence Breakdown"
                )
            
            # ========== Tab 5: Metadata Fields ==========
            with gr.Tab("🏷️ Metadata Fields", id="metadata"):
                gr.Markdown("### Generated FAIR-DS Metadata Fields")
                
                metadata_output = gr.Markdown(
                    value="No metadata fields yet. Process a document first.",
                    label="Metadata Fields by ISA Sheet"
                )
                
                metadata_json_output = gr.Code(
                    language="json",
                    label="Metadata JSON",
                    visible=False
                )
                
                show_metadata_json_btn = gr.Button("📋 Show Metadata JSON")
                show_metadata_json_btn.click(
                    fn=lambda: gr.update(visible=True),
                    outputs=metadata_json_output,
                    queue=False  # 快速 UI 更新不需要队列
                )
            
            # ========== Tab 6: Download Artifacts ==========
            with gr.Tab("📦 Download", id="download"):
                gr.Markdown("### Download Generated Artifacts")
                
                output_dir_display = gr.Textbox(
                    label="Output Directory",
                    value="",
                    interactive=False
                )
                
                with gr.Row():
                    gr.File(
                        label="📄 Metadata JSON (FAIR-DS)",
                        interactive=False
                    )
                    gr.File(
                        label="📊 Workflow Report",
                        interactive=False
                    )
        
        # ========== 配置区（可交互） ==========
        with gr.Accordion("⚙️ Configuration", open=False):
            gr.Markdown("""
            ### LLM and Environment Settings
            💡 **Tip**: 修改这些参数会在处理时创建临时配置文件，
            覆盖默认的 .env 配置
            """)

            with gr.Row():
                llm_provider_input = gr.Dropdown(
                    choices=["openai", "anthropic", "qwen", "ollama"],
                    label="LLM Provider",
                    value=config.llm_provider,
                    interactive=True
                )
                llm_model_input = gr.Textbox(
                    label="Model Name",
                    value=config.llm_model,
                    interactive=True
                )

            with gr.Row():
                llm_temp_input = gr.Slider(
                    minimum=0.0,
                    maximum=2.0,
                    step=0.1,
                    label="Temperature",
                    value=config.llm_temperature,
                    interactive=True
                )
                llm_tokens_input = gr.Number(
                    label="Max Tokens",
                    value=config.llm_max_tokens,
                    interactive=True
                )

            mineru_enabled_input = gr.Checkbox(
                label="Enable MinerU (High-fidelity PDF parsing)",
                value=config.mineru_enabled,
                interactive=True
            )

            langsmith_key_input = gr.Textbox(
                label="LangSmith API Key (for tracing)",
                type="password",
                value=os.getenv("LANGSMITH_API_KEY", ""),
                interactive=True,
                placeholder="sk-..."
            )
        
        # ========== 事件绑定 ==========

        # 流式处理 - 只更新进度显示（传入配置参数）
        # 使用 show_progress 显示进度条，使用 concurrency_limit 限制并发
        process_btn.click(
            fn=process_document_stream,
            inputs=[
                file_input, project_name,
                llm_provider_input, llm_model_input,
                llm_temp_input, llm_tokens_input,
                mineru_enabled_input, langsmith_key_input
            ],
            outputs=[stream_output],
            api_name="process_stream",
            show_progress="full",  # 显示完整进度条
            concurrency_limit=1,  # 限制同时只能处理一个文档
            concurrency_id="document_processing"  # 共享队列
        ).then(
            # 处理完成后，获取完整结果并更新所有标签页
            fn=process_document_full,
            inputs=[
                file_input, project_name,
                llm_provider_input, llm_model_input,
                llm_temp_input, llm_tokens_input,
                mineru_enabled_input, langsmith_key_input
            ],
            outputs=[result_state, status_display, output_dir_state],
            concurrency_id="document_processing"  # 共享队列
        ).then(
            # 更新结果摘要（快速操作，不需要队列）
            fn=lambda r: (
                r if r else None,
                r.get("confidence_scores", {}).get("critic", 0.0) if r else 0.0,
                r.get("confidence_scores", {}).get("structural", 0.0) if r else 0.0,
                r.get("confidence_scores", {}).get("validation", 0.0) if r else 0.0,
                r.get("confidence_scores", {}).get("overall", 0.0) if r else 0.0,
                r.get("execution_summary", {}).get("total_steps", 0) if r else 0,
                r.get("execution_summary", {}).get("successful_steps", 0) if r else 0,
                r.get("execution_summary", {}).get("failed_steps", 0) if r else 0,
                r.get("execution_summary", {}).get("steps_requiring_retry", 0) if r else 0,
            ),
            inputs=[result_state],
            outputs=[
                result_json,
                conf_critic,
                conf_structural,
                conf_validation,
                conf_overall,
                exec_total,
                exec_success,
                exec_failed,
                exec_retry,
            ],
            queue=False  # 快速 UI 更新不需要队列
        ).then(
            # 更新执行历史（快速操作）
            fn=format_execution_history,
            inputs=[result_state],
            outputs=[history_output],
            queue=False
        ).then(
            # 更新置信度详情（快速操作）
            fn=format_confidence_details,
            inputs=[result_state],
            outputs=[confidence_output],
            queue=False
        ).then(
            # 更新元数据字段（快速操作）
            fn=format_metadata_fields,
            inputs=[result_state],
            outputs=[metadata_output, metadata_json_output],
            queue=False
        ).then(
            # 更新输出目录（快速操作）
            fn=lambda d: d,
            inputs=[output_dir_state],
            outputs=[output_dir_display],
            queue=False
        )
    
    return demo


# ============ 主函数 ============

def main():
    """启动 Gradio 应用"""
    
    # 设置日志
    logging.basicConfig(
        level=logging.INFO,
        format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    )
    
    # 应用环境变量配置
    apply_env_overrides(config)
    
    # 创建界面
    demo = create_gradio_interface()
    
    # 配置队列（根据 Gradio 最佳实践）
    # max_size: 最大队列大小，防止用户等待时间过长
    # default_concurrency_limit: 默认并发限制，控制资源使用
    demo.queue(
        max_size=5,  # 最多排队 5 个请求
        default_concurrency_limit=1  # 同时只处理 1 个文档（因为处理很耗时）
    )
    
    # 启动服务
    logger.info("🚀 Starting Gradio UI...")
    logger.info(f"📊 LLM: {config.llm_provider}/{config.llm_model}")
    logger.info(f"🔧 MinerU: {'Enabled' if config.mineru_enabled else 'Disabled'}")
    
    demo.launch(
        server_name="0.0.0.0",
        server_port=7860,
        share=False,
        show_error=True,  # 显示错误信息
        max_threads=40,  # 增加线程池大小以支持更多并发
        footer_links=["api", "gradio", "settings"],  # Gradio 6: 替代 show_api
    )


if __name__ == "__main__":
    main()

